version: '3'

services:
  mongo:
    image: mongo:3
    restart: always
    ports:
      - 27991:27017
    volumes:
      - ./data/mongo:/data/db
      - ./scripts:/scripts
    environment:
      - CONTAINER=docker
    command: [ "--storageEngine", "wiredTiger", "--auth"]
